<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="idea-PC" name="Command line test" tests="3" failures="2" timestamp="20 Feb 2016 07:46:04 GMT" time="5.874" errors="0">
  <testcase name="" time="0.392" classname="gapp.model.dao.ApplicationDaoTest">
    <failure type="org.springframework.dao.EmptyResultDataAccessException" message="No entity found for query; nested exception is javax.persistence.NoResultException: No entity found for query">
      <![CDATA[org.springframework.dao.EmptyResultDataAccessException: No entity found for query; nested exception is javax.persistence.NoResultException: No entity found for query
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:392)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:418)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy36.getDept(Unknown Source)
	at gapp.model.dao.ApplicationDaoTest.getApplications(ApplicationDaoTest.java:19)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
Caused by: javax.persistence.NoResultException: No entity found for query
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:290)
	at gapp.model.dao.jpa.ApplicationDaoImpl.getDept(ApplicationDaoImpl.java:22)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	... 41 more
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="0.043" classname="gapp.model.dao.DepartmentDaoTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at gapp.model.dao.DepartmentDaoTest.getDepartments(DepartmentDaoTest.java:19)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="0.061" classname="gapp.model.dao.UserDaoTest"/>
</testsuite> <!-- Command line test -->
